name: foxfund_alpha
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^5.0.0
  dio: ^4.0.0
  adaptive_dialog: ^0.10.0+5
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  google_fonts: ^2.0.0
  get_it: ^7.1.3
  url_launcher: ^6.0.3
  cached_network_image: ^3.0.0
  flutter_svg: ^0.22.0
  flutter_staggered_grid_view: ^0.3.2
  another_flushbar: ^1.10.20
  logger: ^1.0.0
  loading_overlay: ^0.3.0
  flutter_spinkit: ^5.0.0
  solid_bottom_sheet: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/